#include<iostream>
using namespace std;

int main()
{
    float var_1;
    float var_2;

    cout<<"Enter the value for first var_1:";
    cin>>var_1;

    cout<<"Enter the value for second var_2:";
    cin>>var_2;

    //multiplication of two value / number
    float mult= var_1 * var_2;


    cout<<"The multiplication of two number is :"<<var_1 * var_2<<endl;
    cout<<"The multiplication of two number is :"<<mult<<endl;
}