/*
if, else if, else flow: ---> Conditional Statement

IF (condition1) ----------- YES ---> [ Execute if-block ]
        |
        NO
        |
        v
ELSE IF (condition2) --- YES ---> [ Execute else-if block ]
        |
        NO
        |
        v
ELSE IF (condition3) --- YES ---> [ Execute else-if block ]
        |
        NO
        |
        v
ELSE -------------------> [ Execute else block ]
*/
