#include<iostream>
// using namespace std;

// int main()
// {
//     // Escape Sequences --->{\n, \t, \v, \', \"}
//     cout<<"Escape Sequences"<<endl;
//     //backslash \n
//     cout<<"Hello \nWorld"<<endl;
//     // backslash \t
//     cout<<"Hello  \t World "<<endl;
//     //backslash \v
//     cout<<"Hello \v World"<<endl;
//     //backslah \'
//     cout<<"Hello \'World\'"<<endl;
//     //baclslash \"
//     cout<<"Hello \"World\""<<endl;
// }