#include<iostream>
using namespace std;

int main()

{
    cout<<"Hello World"<<endl; // this is a single line comments and this will display the Hello World

    cout<<"hello ! this is Multi line Comment"<<endl;

    /*

    this is C++ 
    this is programming
    this is Comments
    
    
    */



    // How to Declare the variable 
    int 1a=10; // wrong 
    int Student_number2 = 200; // correct 
}